
<table id="tblstudents" class="grid">
    <thead>
        <tr>
            <th>
                S. No.
            </th>
            <th>
                Student Name
            </th>
            <th>
                Total Marks
            </th>
            <th>
                Grade
            </th>
        </tr>
    </thead>
    <tr>
        <td>
            1
        </td>
        <td>
            Ravi
        </td>
        <td>
            500
        </td>
        <td>
            2
        </td>
    </tr>
    <tr>
        <td>
            2
        </td>
        <td>
            Suresh
        </td>
        <td>
            600
        </td>
        <td>
            1
        </td>
    </tr>
    <tr>
        <td>
            3
        </td>
        <td>
            Steave
        </td>
        <td>
            500
        </td>
        <td>
            2
        </td>
    </tr>
    <tr>
        <td>
            4
        </td>
        <td>
            Kishore
        </td>
        <td>
            400
        </td>
        <td>
            3
        </td>
    </tr>
    <tr>
        <td>
            5
        </td>
        <td>
            Vinay
        </td>
        <td>
            300
        </td>
        <td>
            4
        </td>
    </tr>
    <tr>
        <td>
            6
        </td>
        <td>
            Sony
        </td>
        <td>
            500
        </td>
        <td>
            2
        </td>
    </tr>
    <tr>
        <td>
            7
        </td>
        <td>
            Laxman
        </td>
        <td>
            600
        </td>
        <td>
            1
        </td>
    </tr>
    <tr>
        <td>
            8
        </td>
        <td>
            Krishna
        </td>
        <td>
            400
        </td>
        <td>
            3
        </td>
    </tr>
</table>